version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: gspadilha
      ME_CONFIG_BASICAUTH_PASSWORD: gspadilha
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: gspadilha
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gspadilha
    ports:
      - "27017:27017"
    volumes:
      - /home/$USER/Desktop/dbs/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
