version: "3"

services:
    com_apache:
        container_name: apache_php_basico

        restart: always

        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - "80:80"
            - "443:443"

        volumes:
            - /home/$USER/Desktop/DEV/www:/var/www/html

        links:
            - bancodedados

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin

        ports:
            - "8080:80"

        depends_on:
            - com_apache
            - bancodedados

        links:
            - "bancodedados:db"

    bancodedados:
        container_name: mariadb
        image: mariadb:latest

        environment:
            MYSQL_DATABASE: developer
            MYSQL_USER: gspadilha
            MYSQL_PASSWORD: gspadilha
            MYSQL_ROOT_PASSWORD: gspadilha

        ports:
            - "3306:3306"

        volumes:
            - /home/$USER/Desktop/dbs/MariaDB:/var/lib/mysql
